/**
 * Instaflow SEO Suite - CRM Adapter Interface & Default Implementations
 *
 * Interface specification:
 * - listClients(): Promise<Client[]>
 * - getClient(id): Promise<Client|null>
 * - saveClient(client): Promise<Client>
 * - deleteClient(id): Promise<boolean>
 * - listReports(clientId?): Promise<Report[]>
 * - getReport(id): Promise<Report|null>
 * - saveReport(report): Promise<Report>
 * - deleteReport(id): Promise<boolean>
 * - createLead(leadData): Promise<Lead>
 * - listLeads(): Promise<Lead[]>
 * - getSettings(): Promise<Settings>
 * - saveSettings(settings): Promise<Settings>
 */

import { getItem, setItem, removeItem } from '../storage/storage.js';

export class LocalStorageCrmAdapter {
  constructor() {
    this.name = 'LocalStorageCrmAdapter';
  }

  async listClients() {
    const clients = getItem('clients', []);
    return Array.isArray(clients) ? clients : [];
  }

  async getClient(id) {
    const clients = await this.listClients();
    return clients.find(c => c.id === id) || null;
  }

  async saveClient(clientData) {
    const clients = await this.listClients();
    const id = clientData.id || `cli_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
    const now = new Date().toISOString();
    const existingIdx = clients.findIndex(c => c.id === id);

    const client = {
      ...clientData,
      id,
      updatedAt: now,
      createdAt: clientData.createdAt || now
    };

    if (existingIdx !== -1) {
      clients[existingIdx] = client;
    } else {
      clients.unshift(client);
    }

    setItem('clients', clients);
    return client;
  }

  async deleteClient(id) {
    const clients = await this.listClients();
    const filtered = clients.filter(c => c.id !== id);
    setItem('clients', filtered);
    return true;
  }

  async listReports(clientId = null) {
    const reports = getItem('reports', []);
    if (!Array.isArray(reports)) return [];
    if (clientId) {
      return reports.filter(r => r.clientId === clientId);
    }
    return reports;
  }

  async getReport(id) {
    const reports = await this.listReports();
    return reports.find(r => r.id === id) || null;
  }

  async saveReport(reportData) {
    const reports = await this.listReports();
    const id = reportData.id || `rep_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
    const now = new Date().toISOString();
    const existingIdx = reports.findIndex(r => r.id === id);

    const report = {
      ...reportData,
      id,
      updatedAt: now,
      createdAt: reportData.createdAt || now
    };

    if (existingIdx !== -1) {
      reports[existingIdx] = report;
    } else {
      reports.unshift(report);
    }

    setItem('reports', reports);
    return report;
  }

  async deleteReport(id) {
    const reports = await this.listReports();
    const filtered = reports.filter(r => r.id !== id);
    setItem('reports', filtered);
    return true;
  }

  async createLead(leadData) {
    const leads = await this.listLeads();
    const id = `lead_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
    const lead = {
      ...leadData,
      id,
      createdAt: new Date().toISOString()
    };
    leads.unshift(lead);
    setItem('leads', leads);
    return lead;
  }

  async listLeads() {
    const leads = getItem('leads', []);
    return Array.isArray(leads) ? leads : [];
  }

  async getSettings() {
    return getItem('settings', {
      proxyUrl: 'https://instaflow-seo-proxy.sujoymoulick05.workers.dev',
      brandName: 'Instaflow Agency',
      brandLogo: '',
      primaryColor: '#6366f1',
      accentColor: '#ec4899',
      contactEmail: 'seo@instaflow.io',
      contactPhone: '+1 (555) 019-2834',
      reportFooter: 'Generated by Instaflow SEO Intelligence Suite',
      reAuditIntervalDays: 30,
      customWeights: {
        onpage: 35,
        geo: 20,
        links: 15,
        usability: 15,
        performance: 15
      }
    });
  }

  async saveSettings(newSettings) {
    const current = await this.getSettings();
    const updated = { ...current, ...newSettings };
    setItem('settings', updated);
    return updated;
  }
}

/**
 * Example HTTP Adapter demonstrating integration with an Instaflow backend
 */
export class InstaflowHttpCrmAdapter {
  constructor(apiBaseUrl = '/api/seo') {
    this.apiBaseUrl = apiBaseUrl;
  }

  async createLead(leadData) {
    const res = await fetch(`${this.apiBaseUrl}/leads`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(leadData)
    });
    if (!res.ok) throw new Error(`Lead submission failed: ${res.statusText}`);
    return res.json();
  }

  async listClients() {
    const res = await fetch(`${this.apiBaseUrl}/clients`);
    return res.json();
  }

  async saveReport(reportData) {
    const res = await fetch(`${this.apiBaseUrl}/reports`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(reportData)
    });
    return res.json();
  }

  async getSettings() {
    const res = await fetch(`${this.apiBaseUrl}/settings`);
    return res.json();
  }

  async saveSettings(settings) {
    const res = await fetch(`${this.apiBaseUrl}/settings`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(settings)
    });
    return res.json();
  }
}
