/**
 * Instaflow SEO Suite - Report Builders (HTML, Markdown, CSV, JSON, Self-Contained Standalone HTML)
 */

import { renderScorecardSVG } from '../../ui/charts.js';

/**
 * Builds clean Markdown audit report
 */
export function buildMarkdownReport(reportData, brandSettings = {}) {
  const sc = reportData.scorecard;
  const brandName = brandSettings.brandName || 'Instaflow SEO Suite';
  const url = reportData.url || 'Pasted HTML / Document';
  const date = new Date(reportData.auditedAt || Date.now()).toUTCString();

  let md = `# SEO & AI-Search Readiness Audit Report\n\n`;
  md += `**Client / Target URL:** ${url}  \n`;
  md += `**Date Generated:** ${date}  \n`;
  md += `**Audited by:** ${brandName}  \n\n`;
  md += `---\n\n`;

  md += `## 1. Executive Summary & Scorecard\n\n`;
  md += `| Category | Score | Grade | Passed | Warnings | Failed |\n`;
  md += `| :--- | :--- | :--- | :--- | :--- | :--- |\n`;

  for (const cat of sc.categories) {
    const scoreStr = cat.score !== null ? `${cat.score}/100` : 'N/A';
    const gradeStr = cat.grade || 'N/A';
    md += `| **${cat.name}** | ${scoreStr} | **${gradeStr}** | ${cat.passed} | ${cat.warned} | ${cat.failed} |\n`;
  }

  md += `\n**Overall Health Score:** **${sc.overallScore !== null ? sc.overallScore + '/100' : 'N/A'} (Grade ${sc.overallGrade})**\n\n`;

  if (sc.topFixes && sc.topFixes.length > 0) {
    md += `## 2. Priority Action Plan (Top Fixes)\n\n`;
    sc.topFixes.forEach((fix, idx) => {
      md += `### ${idx + 1}. [${fix.severity.toUpperCase()}] ${fix.title}\n`;
      md += `- **Detected:** ${fix.value || 'Issue detected'}\n`;
      md += `- **Details:** ${fix.details}\n`;
      md += `- **Recommended Action:** ${fix.details}\n\n`;
    });
  }

  md += `## 3. Comprehensive Audit Breakdown\n\n`;
  const checks = reportData.checkResults || [];
  for (const cat of sc.categories) {
    const catChecks = checks.filter(c => c.scorecardGroup === cat.id);
    if (catChecks.length === 0) continue;

    md += `### ${cat.name} (${cat.score !== null ? cat.score + '/100' : 'N/A'})\n\n`;
    for (const c of catChecks) {
      const icon = c.status === 'pass' ? '✅' : c.status === 'warn' ? '⚠️' : c.status === 'fail' ? '❌' : '⚪';
      md += `- ${icon} **${c.title}** (${c.status.toUpperCase()}): ${c.value || ''} - ${c.details}\n`;
    }
    md += `\n`;
  }

  md += `---\n*Generated by ${brandName} - Powered by Instaflow SEO Suite*\n`;
  return md;
}

/**
 * Builds CSV Export
 */
export function buildCsvReport(reportData) {
  const rows = [
    ['Check ID', 'Category', 'Scorecard Group', 'Check Title', 'Status', 'Severity', 'Effort', 'Value', 'Details']
  ];

  for (const c of (reportData.checkResults || [])) {
    rows.push([
      c.id,
      c.category,
      c.scorecardGroup,
      c.title,
      c.status,
      c.severity,
      c.effort || 'medium',
      c.value || '',
      (c.details || '').replace(/"/g, '""')
    ]);
  }

  return rows.map(r => r.map(cell => `"${cell}"`).join(',')).join('\n');
}

/**
 * Builds JSON Export
 */
export function buildJsonReport(reportData) {
  return JSON.stringify(reportData, null, 2);
}

/**
 * Builds Self-Contained Branded Single-File HTML / PDF-Ready Report
 */
export function buildStandaloneHtmlReport(reportData, brandSettings = {}) {
  const brandName = brandSettings.brandName || 'Instaflow SEO Intelligence';
  const logo = brandSettings.brandLogo || '';
  const primaryColor = brandSettings.primaryColor || '#4f46e5';
  const accentColor = brandSettings.accentColor || '#ec4899';
  const footerText = brandSettings.reportFooter || 'Instaflow SEO Suite • Confidential Audit';
  const date = new Date(reportData.auditedAt || Date.now()).toUTCString();
  const sc = reportData.scorecard;

  const svgScorecard = renderScorecardSVG(sc, { width: 700, height: 260 });

  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SEO & GEO Audit Report - ${reportData.url || 'Site Audit'}</title>
  <style>
    :root {
      --primary: ${primaryColor};
      --accent: ${accentColor};
      --bg: #f8fafc;
      --surface: #ffffff;
      --text: #0f172a;
      --muted: #64748b;
      --border: #e2e8f0;
      --pass: #10b981;
      --warn: #f59e0b;
      --fail: #ef4444;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: var(--bg); color: var(--text); line-height: 1.5; padding: 2rem; }
    .container { max-width: 900px; margin: 0 auto; background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: 2.5rem; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05); }
    .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid var(--border); padding-bottom: 1.5rem; margin-bottom: 2rem; }
    .logo { max-height: 48px; max-width: 180px; }
    .brand-title { font-size: 1.5rem; font-weight: 700; color: var(--primary); }
    .meta { font-size: 0.875rem; color: var(--muted); margin-top: 0.25rem; }
    .scorecard-card { background: #f8fafc; border: 1px solid var(--border); border-radius: 8px; padding: 1.5rem; margin-bottom: 2rem; }
    .section-title { font-size: 1.25rem; font-weight: 700; margin: 2rem 0 1rem 0; border-left: 4px solid var(--primary); padding-left: 0.75rem; }
    .fix-item { background: #fff; border: 1px solid var(--border); border-left: 4px solid var(--fail); border-radius: 6px; padding: 1rem; margin-bottom: 0.75rem; }
    .fix-item.warn { border-left-color: var(--warn); }
    .fix-title { font-weight: 600; font-size: 1rem; }
    .fix-detail { font-size: 0.875rem; color: var(--muted); margin-top: 0.25rem; }
    .checks-table { width: 100%; border-collapse: collapse; margin-top: 1rem; font-size: 0.875rem; }
    .checks-table th, .checks-table td { padding: 0.75rem; text-align: left; border-bottom: 1px solid var(--border); }
    .checks-table th { background: #f1f5f9; font-weight: 600; }
    .badge { display: inline-block; padding: 0.2rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 700; text-transform: uppercase; }
    .badge-pass { background: #d1fae5; color: #065f46; }
    .badge-warn { background: #fef3c7; color: #92400e; }
    .badge-fail { background: #fee2e2; color: #991b1b; }
    .badge-na { background: #f1f5f9; color: #475569; }
    .footer { text-align: center; margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid var(--border); font-size: 0.8rem; color: var(--muted); }
    @media print {
      body { background: #fff; padding: 0; }
      .container { border: none; box-shadow: none; padding: 0; max-width: 100%; }
      .page-break { page-break-before: always; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div>
        ${logo ? `<img src="${logo}" class="logo" alt="Logo" />` : `<div class="brand-title">${brandName}</div>`}
        <div class="meta">Audit Target: <strong>${reportData.url || 'Pasted Document'}</strong></div>
        <div class="meta">Generated: ${date}</div>
      </div>
      <div style="text-align: right;">
        <button class="no-print" onclick="window.print()" style="padding: 0.5rem 1rem; background: var(--primary); color: #fff; border: none; border-radius: 6px; cursor: pointer; font-weight: 600;">🖨️ Print / Save PDF</button>
      </div>
    </div>

    <div class="scorecard-card">
      <h2 style="font-size: 1.1rem; margin-bottom: 1rem; font-weight: 700;">Executive Scorecard</h2>
      ${svgScorecard}
    </div>

    ${sc.topFixes && sc.topFixes.length > 0 ? `
      <h3 class="section-title">Top Priority Fixes</h3>
      ${sc.topFixes.map(f => `
        <div class="fix-item ${f.status === 'warn' ? 'warn' : ''}">
          <div class="fix-title">${f.status === 'fail' ? '❌' : '⚠️'} [${f.severity.toUpperCase()}] ${f.title}</div>
          <div class="fix-detail"><strong>Detected:</strong> ${f.value || 'Issue detected'}</div>
          <div class="fix-detail"><strong>Recommendation:</strong> ${f.details}</div>
        </div>
      `).join('')}
    ` : ''}

    <div class="page-break"></div>
    <h3 class="section-title">Detailed Check Results</h3>
    <table class="checks-table">
      <thead>
        <tr>
          <th>Category</th>
          <th>Check</th>
          <th>Status</th>
          <th>Detected Value / Note</th>
        </tr>
      </thead>
      <tbody>
        ${(reportData.checkResults || []).map(c => `
          <tr>
            <td style="font-weight: 600; text-transform: capitalize;">${c.scorecardGroup || c.category}</td>
            <td><strong>${c.title}</strong></td>
            <td><span class="badge badge-${c.status}">${c.status}</span></td>
            <td>${c.value || c.details || '-'}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>

    <div class="footer">
      ${footerText}
    </div>
  </div>
</body>
</html>`;

  return html;
}
